apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: superhero-api-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "pods", "services", "persistentvolumeclaims"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "update", "delete"] 